### ISSUE TITLE
Criacao de coletaneas demorada

### ISSUE THREAD

**Issue by rudsondant** [wendellpbarreto/tronco#1]
Segundo relato de um usuário do sistema:
"Nunca consegui criar uma coletânea. Monto as peças, quando vou adicioná-las para formar uma coletânea a página demora bastante para carregar, e no fim dá erro. Penso que este seja a principal falha do site, pois os materiais que tentei anexar as coletâneas são as fotos e vídeos"

**Comment by rudsondant** [comment]
Paula relatou que:
"A criação de coletâneas com videos não funciona bem no módulo de criação, mas o vídeo é exibido na apresentação"

**Comment by rudsondant** [comment]
Só uma dúvida: o problema foi ressolvido, e o site foi atualizado para a versão já sem o problema?

**Comment by wendellpbarreto** [comment]
Ainda não, @rudsondant. Esse erro se deu por causa da versão do PostgreSQL, está sendo bem chato de se resolver. Principalmente porque eu não consigo reproduzir o erro no meu computador,

**Comment by wendellpbarreto** [comment]
Finalizado!

**Comment by rudsondant** [comment]
Ok, então esse erro está condicionado há certos tipos de máquinas e não é um erro geral. Qual o SO da sua máquina e qual navegador? E qual dos dois tem mais potencial para geraroo erro SO ou navegador? Presumo que seja navegador. Seria mais fácil limitar o uso para certos tipos de navegadores.
