### ISSUE TITLE
Apagar/Criar coletanea principal

### ISSUE THREAD

**Issue by rudsondant** [wendellpbarreto/tronco#10]
O que ocorre se coletanea principal for apagada?
Como usuário pode fazer para criar ela novamente?

**Comment by wendellpbarreto** [comment]
Do que eu me lembro ela não pode ser apagada, se for, ela volta a ser criada no automático.

**Comment by rudsondant** [comment]
Ok otimo. Vou textar no MCC.

**Comment by rudsondant** [comment]
Testado. Ele surge automaticamente e se apagada ele volta sozinha, apenas vazia é claro.
