### ISSUE TITLE
Erro nas Peças

### ISSUE THREAD

**Issue by rudsondant** [wendellpbarreto/tronco#2]
Um usuário do sistema reportou o seguinte erro:
"Quando tento criar peças e/ou editá-las também dá erro e aparece isto “UnicodeEncodeError at / ....”

**Comment by wendellpbarreto** [comment]
@rudsondant, criei peças e tudo ocorreu normalmente. Preciso da imagem da tela de erro pois não consegui reproduzi-lo.

**Comment by rudsondant** [comment]
Me informe o SO e navegador que você está fazendo os testes. Muitas vezes erros não reproduziveis em sistemas web se devem ao fato que certos  navegadores não suportam determinada ação do sistema.

**Comment by wendellpbarreto** [comment]
OS X Yosemite - Google Chrome.

**Comment by wendellpbarreto** [comment]
![er](https://cloud.githubusercontent.com/assets/2782873/6646824/6ab596c4-c9a7-11e4-960b-b8c49ab75edc.png)

**Comment by rudsondant** [comment]
segue
![erro](https://cloud.githubusercontent.com/assets/4387955/6647147/20b27382-c9aa-11e4-971f-e727f8223e8d.png)

**Comment by rudsondant** [comment]
Alguma novidade sobre essa issue?

**Comment by rudsondant** [comment]
Creio que essa issue foi ressolvida. Podemos fecha-la?

**Comment by rudsondant** [comment]
Oi. Creio que essa issue foi ressolvida. Podemos fecha-la?

**Comment by rudsondant** [comment]
Oi @wendellpbarreto. Creio que essa tarefa foi concluida, podemos fecha-la?

**Comment by wendellpbarreto** [comment]
Sim.
