### ISSUE TITLE
Descricao para midias

### ISSUE THREAD

**Issue by rudsondant** [wendellpbarreto/tronco#21]
As peças do museu podem ter assocaidos a elas muitos imagens e videos. Mas uma peça tem uma descriçao unica. A ideia, é que cada imagem, video, etc, alem de poder ter um autor proprio, possa ter tambem uma descricao propria, ou seja adicionar um campo para descricao na peça.

**Comment by PaulaRoberta** [comment]
Sim, adicionei o campo descrição no modelo de imagem.

**Comment by rudsondant** [comment]
Ok. Otimo. O mesmo deve ser feito para os videos.

**Comment by PaulaRoberta** [comment]
Adicionei o campo descrição no modelo de vídeo.

**Comment by rudsondant** [comment]
Muito bom! Essa tarefa merece um premio quando for concluida :+1: . É uma demanda antiga do sistema que estava sendo negligenciada.

**Comment by PaulaRoberta** [comment]
commit b66ff23f26b1b0265f57188f397fd3325bd42244

**Comment by PaulaRoberta** [comment]
Adicionei o campo descrição no modelo de áudio.

**Comment by PaulaRoberta** [comment]
Adicionei o campo descrição no modelo de documento
