### ISSUE TITLE
Erro no gerenciamento : noticia

### ISSUE THREAD

**Issue by rudsondant** [wendellpbarreto/tronco#23]
Segundo um usuário do sistema: Encontrei outro erro agora.... tentei inserir uma notícia através do "gerenciamento" (normalmente uso a ferramenta "criação") e deu um bug. Coloquei imagens e inseri uma peça na notícia e não deu certo.

**Comment by PaulaRoberta** [comment]
Eu testei aqui e deu certo inserir uma notícia através do gerenciamento. Só não aparece a peça e a imagem nela.

**Comment by rudsondant** [comment]
Ok, entao deve ser aquele erro que vc reportou na issue #22. Devem ter a mesma fonte. No caso a solucao é fazer a imagem aparecer na noticia. Assim reponde a questao da issue #22 e ressolve esse bug. @PaulaRoberta, caso vc tenha idea de como ressolver, assine essa tarefa a voce.

**Comment by PaulaRoberta** [comment]
@rudsondant tenho uma dúvida, mostrei a imagem de intervenção na notícia. Em relação as peças, elas vão ser mesmo mostradas na notícia em si?

**Comment by rudsondant** [comment]
Oi @PaulaRoberta, eu creio que seja melhor permitir que as pecas sejam colocadas na noticia sim. Do contrario as noticias seriam pouco atrativas.

**Comment by PaulaRoberta** [comment]
![captura de tela de 2015-04-26 14 56 07](https://cloud.githubusercontent.com/assets/10801652/7338526/c99134ba-ec24-11e4-9ae7-caca90a23f59.png)
![captura de tela de 2015-04-26 14 55 08](https://cloud.githubusercontent.com/assets/10801652/7338527/d15ca512-ec24-11e4-9a76-df9a339c8e3b.png)
![captura de tela de 2015-04-26 14 58 54](https://cloud.githubusercontent.com/assets/10801652/7338530/d826ffe6-ec24-11e4-8d22-53a6f44f0bf9.png)
![captura de tela de 2015-04-26 14 56 56](https://cloud.githubusercontent.com/assets/10801652/7338533/de7aff00-ec24-11e4-9c0a-c09396408078.png)

Estou enviando algumas fotos para o senhor dar sua opinião.

**Comment by PaulaRoberta** [comment]
@rudsondant

**Comment by rudsondant** [comment]
Oi @PaulaRoberta. Ok, ficou muito bom.

**Comment by PaulaRoberta** [comment]
@rudsondant é melhor deixar as notícias assim:
![captura de tela de 2015-05-01 15 05 43](https://cloud.githubusercontent.com/assets/10801652/7434745/94d00420-f013-11e4-9487-4ea6648f8629.png)
ou assim: (sendo que a imagem iria aparecer quando clicasse, igual a segunda foto que mandei anteriormente)
![captura de tela de 2015-05-01 15 07 24](https://cloud.githubusercontent.com/assets/10801652/7434759/cbadeff2-f013-11e4-9b20-213233b5f9b2.png)

**Comment by rudsondant** [comment]
@PaulaRoberta a opção 2 é melhor.

**Comment by PaulaRoberta** [comment]
ok
