### ISSUE TITLE
Informações de Contato

### ISSUE THREAD

**Issue by rudsondant** [wendellpbarreto/tronco#8]
As informações de Contato do museu não podem ser alteradas. Elas estão amarradas na página de apresentação (no canto inferior esquerdo). Lá está os dados de contato do MCC, mesmo no museu Tronco. O pessoal do tronco deseja alterar para o contato deles, contudo nem no gerenciamento é possivel mudar (pelo menos eu não encontrei onde alterar).

**Comment by wendellpbarreto** [comment]
Esses valores estão estáticos, dá pra mudar diretamente ou criar uma parte pra isso. @rudsondant.

**Comment by rudsondant** [comment]
É melhor criar uma parte para isso, pois dá ao usuário independencia. Mudar diretamente obrigaria eles a nos contatar a cada mudança.

Você pode cuidar da criação dessa funcionalidade?

**Comment by rudsondant** [comment]
Alguma novidade sobre essa issue?

**Comment by wendellpbarreto** [comment]
Não tinha percebido sua resposta. Posso tomar conta disso sim. Vou implementar.

**Comment by rudsondant** [comment]
Alguma novidade nesta Issue. Eles perguntara-me novamente sobre este ponto.

**Comment by rudsondant** [comment]
Alguma novidade nesta Issue.

**Comment by rudsondant** [comment]
Oi @wendellpbarreto. Alguma novidade nessa tarefa?
