### ISSUE TITLE
Ordenacao das noticias ao contrario

### ISSUE THREAD

**Issue by rudsondant** [wendellpbarreto/tronco#9]
No site de apresentacao, as ultimas noticias estao sendo exibidas na ordem contraria, ou seja da noticia mais antiga para a mais nova, quando deveria ser o oposto.

**Comment by rudsondant** [comment]
Vou presumir então @PaulaRoberta que você sabe como ressolver essa questão. Estou assinando a você a tarefa.

**Comment by rudsondant** [comment]
Oi @PaulaRoberta, creio que já podemos colocar o label On going nessa tarefa, para nosso controle. Se sim, peço que coloque.Isso facilita o controle das tarefas.

**Comment by rudsondant** [comment]
Otimo. Mas noite, que na página inicial  de apresentação, logo após a região das coletaneas, vem as notiticas, no caso as ultimas noticias. Aqui nesse ponto elas continuam ordenadas ao contrário.

**Comment by PaulaRoberta** [comment]
Eu resolvi isso no comite 341daa5ed25571b56b11d9f4a338042db6497e1a . Pois vi que a ordenação estava feita pela data de criação e não pelo id. E acabei comitando em outra issue depois que vi esse erro.

**Comment by rudsondant** [comment]
Otimo
